# Standard screenshot and portal permissions.
permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(bin|local/bin)/slurp, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/bin/waybar, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
